# Generated by Django 3.2.4 on 2021-06-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "variable",
                    models.CharField(
                        max_length=254, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("value", models.TextField()),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
                "default_permissions": (),
            },
        ),
    ]
