# Generated by Django 3.2.3 on 2021-05-23 23:15

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import aa_forum.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("aa_forum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalMessages",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_sent", models.DateTimeField(default=django.utils.timezone.now)),
                ("subject", models.CharField(default="", max_length=254)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=models.SET(aa_forum.models.get_sentinel_user),
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=models.SET(aa_forum.models.get_sentinel_user),
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Message",
                "verbose_name_plural": "Personal Messages",
                "default_permissions": (),
            },
        ),
    ]
