# Generated by Django 3.2.4 on 2021-06-03 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slugs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Slug",
                "verbose_name_plural": "Slugs",
                "default_permissions": (),
            },
        ),
        migrations.AlterField(
            model_name="boards",
            name="slug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="aa_forum.slugs",
            ),
        ),
        migrations.AlterField(
            model_name="categories",
            name="slug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="aa_forum.slugs",
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="slug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="aa_forum.slugs",
            ),
        ),
        migrations.AlterField(
            model_name="personalmessages",
            name="slug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="aa_forum.slugs",
            ),
        ),
    ]
