# Generated by Django 3.2.4 on 2021-06-03 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0002_auto_20210603_0727"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="slug",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="aa_forum.slugs",
            ),
        ),
    ]
