# Generated by Django 3.2.4 on 2021-06-03 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0003_alter_categories_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boards",
            name="slug",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="aa_forum.slugs",
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="slug",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="aa_forum.slugs",
            ),
        ),
        migrations.AlterField(
            model_name="personalmessages",
            name="slug",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="aa_forum.slugs",
            ),
        ),
    ]
