# Generated by Django 3.2.4 on 2021-06-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0003_default_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_plaintext",
            field=models.TextField(blank=True),
        ),
    ]
