# Generated by Django 3.1.10 on 2021-06-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0004_auto_20210618_1204"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lastmessageseen",
            options={"default_permissions": ()},
        ),
    ]
