# Generated by Django 3.2.4 on 2021-06-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("aa_forum", "0005_auto_20210603_1451"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boards",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="aa_forum_boards_group_restriction",
                to="auth.Group",
            ),
        ),
    ]
