# Generated by Django 3.1.10 on 2021-06-14 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0005_remove_board_from_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="message",
            name="time_modified",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="slug",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="time_modified",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
