# Generated by Django 3.1.10 on 2021-06-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0005_auto_20210619_1247"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lastmessageseen",
            index=models.Index(
                fields=["topic", "user", "message_time"],
                name="lastmessageseen_compounded",
            ),
        ),
    ]
