# Generated by Django 3.1.10 on 2021-06-15 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0006_add_indices"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={
                "default_permissions": (),
                "verbose_name": "topic",
                "verbose_name_plural": "topics",
            },
        ),
        migrations.RemoveField(
            model_name="topic",
            name="time_modified",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="user_started",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="user_updated",
        ),
        migrations.AddField(
            model_name="board",
            name="first_message",
            field=models.ForeignKey(
                default=None,
                editable=False,
                help_text="Shortcut for better performance",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="aa_forum.message",
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="last_message",
            field=models.ForeignKey(
                default=None,
                editable=False,
                help_text="Shortcut for better performance",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="aa_forum.message",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="first_message",
            field=models.ForeignKey(
                default=None,
                editable=False,
                help_text="Shortcut for better performance",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="aa_forum.message",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="last_message",
            field=models.ForeignKey(
                default=None,
                editable=False,
                help_text="Shortcut for better performance",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="aa_forum.message",
            ),
        ),
    ]
