# Generated by Django 3.1.10 on 2021-06-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0006_auto_20210619_1706"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="time_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="time_posted",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
