# Generated by Django 3.2.4 on 2021-06-04 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("aa_forum", "0006_alter_boards_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="topics",
            name="read_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="aa_forum_read_topics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
