# Generated by Django 3.2.4 on 2021-06-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0007_topics_read_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topics",
            options={
                "default_permissions": (),
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
            },
        ),
        migrations.RemoveField(
            model_name="topics",
            name="first_message",
        ),
        migrations.RemoveField(
            model_name="topics",
            name="last_message",
        ),
    ]
