# Generated by Django 3.1.10 on 2021-06-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0007_add_first_and_last_message_shortcuts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="num_replies",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="num_views",
        ),
        migrations.AlterField(
            model_name="message",
            name="time_modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="time_posted",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="personalmessage",
            name="time_sent",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="slug",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
    ]
