# Generated by Django 3.1.10 on 2021-06-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0007_auto_20210619_1711"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="order",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
