# Generated by Django 3.1.10 on 2021-06-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0008_migrate_to_add_now"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="variable",
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name="setting",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="board",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="board",
            name="name",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="board",
            name="slug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="aa_forum.slug",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="aa_forum.slug",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personalmessage",
            name="message",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personalmessage",
            name="slug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="aa_forum.slug",
            ),
        ),
        migrations.AlterField(
            model_name="personalmessage",
            name="subject",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="aa_forum.slug",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="subject",
            field=models.CharField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.UniqueConstraint(
                fields=("category", "name"), name="fpk_board"
            ),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                fields=("board", "subject"), name="fpk_topic"
            ),
        ),
    ]
