# Generated by Django 3.2.4 on 2021-06-04 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0008_auto_20210604_0849"),
    ]

    operations = [
        migrations.AddField(
            model_name="topics",
            name="time_modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
