# Generated by Django 3.1.10 on 2021-06-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0008_auto_20210619_1715"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="last_message_seen",
        ),
    ]
