# Generated by Django 3.2.4 on 2021-06-04 08:58

from django.conf import settings
from django.db import migrations, models

import aa_forum.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("aa_forum", "0009_topics_time_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="user_updated",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(aa_forum.models.get_sentinel_user),
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
