# Generated by Django 3.2.4 on 2021-06-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0010_alter_messages_user_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topics",
            options={
                "default_permissions": (),
                "ordering": ["-time_modified"],
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
            },
        ),
    ]
