# Generated by Django 4.0.7 on 2022-08-27 17:09

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0011_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalmessage",
            name="slug",
        ),
    ]
