# Generated by Django 4.0.7 on 2022-08-25 23:32

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0011_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="user_signature_length",
            field=models.IntegerField(
                default=750,
                help_text="Maximum length of a users signature",
                verbose_name="User signature length",
            ),
        ),
    ]
