# Generated by Django 4.0.7 on 2022-08-27 18:52

# Django
from django.db import migrations

# ckEditor
import ckeditor_uploader.fields


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0012_remove_personalmessage_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalmessage",
            name="message",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
