# Generated by Django 4.0.7 on 2022-08-28 16:51

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0013_alter_personalmessage_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalmessage",
            name="deleted_by_recipient",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personalmessage",
            name="deleted_by_sender",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personalmessage",
            name="message_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="aa_forum.personalmessage",
            ),
        ),
    ]
