# Generated by Django 4.0.10 on 2023-09-22 19:39

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aa_forum", "0014_userprofile_discord_dm_on_new_personal_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="use_webhook_for_replies",
            field=models.BooleanField(
                default=False,
                help_text="Use this Discord webhook for replies as well? When activated every reply to any topic in this board will be posted to the defined Discord channel. (Child boards are excluded) Chose wisely! (Default: NO)",
            ),
        ),
    ]
