# Generated by Django 4.2.11 on 2024-03-08 14:01

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0017_switch_to_ckeditor_5"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="show_unread_personal_messages_dashboard_widget",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_unread_topics_dashboard_widget",
            field=models.BooleanField(default=False),
        ),
    ]
