# Generated by Django 5.2.16 on 2026-07-08 09:19

# Django
import django.db.models.deletion
from django.db import migrations, models

# AA Forum
import aa_forum.models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_forum", "0018_alter_board_announcement_groups_and_more"),
        ("authentication", "0026_alter_characterownership_user_and_more"),
        ("groupmanagement", "0021_alter_authgroup_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="announcement_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "User in at least one of the selected groups will be able to start "
                    'topics in "Announcement Boards". If no group is selected, '
                    "only forum admins can do so. This setting will not be inherited "
                    "to child boards. (Hint: These restrictions only take effect when a "
                    'board is marked as "Announcement Board", see checkbox above.)'
                ),
                related_name="aa_forum_boards_group_start_topic_restriction",
                to="groupmanagement.group",
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "This will restrict access to this board to the selected groups. "
                    "If no groups are selected, everyone who can access the forum can "
                    "also access this board. (This setting is optional)"
                ),
                related_name="aa_forum_boards_group_restriction",
                to="groupmanagement.group",
            ),
        ),
        migrations.AlterField(
            model_name="lastmessageseen",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aa_forum_last_message_seen",
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="user_created",
            field=models.ForeignKey(
                on_delete=models.SET(aa_forum.models.get_sentinel_user),
                related_name="+",
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="user_updated",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(aa_forum.models.get_sentinel_user),
                related_name="+",
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="personalmessage",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="personalmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="authentication.user",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="aa_forum_user_profile",
                serialize=False,
                to="authentication.user",
            ),
        ),
    ]
